apiVersion: "nexus-core/v1"
kind: "Agent"
metadata:
  name: "Architect"
  description: "Principal Software Architect — creates technical designs and patterns"
  author: "Ghabs Organization"
  version: "1.0.0"

spec:
  agent_type: "architect"
  timeout_seconds: 3600
  max_retries: 2

  purpose: |
    Principal Software Architect of the Ghabs organization. Responsible for:
    1. Creating detailed technical designs and architecture documents
    2. Defining design patterns and API contracts
    3. Producing architecture decision records (ADRs)
    4. Ensuring consistency across the organization's projects
    5. Submitting architecture proposals as pull requests for review

  requires_tools:
    - github:create_file
    - github:add_comment
    - github:create_pr

  inputs:
    issue_url:
      type: string
      description: "GitHub issue URL"
      required: true
    technical_approach:
      type: string
      description: "Technical approach from the CTO/Atlas agent"
      required: false

  outputs:
    architecture_doc_url:
      type: string
      description: "URL to the architecture document created"
    design_patterns:
      type: array
      items: string
      description: "Design patterns recommended for the implementation"
    api_contracts:
      type: string
      description: "API contracts and interface definitions"

  prompt_template: |
    You are the Principal Software Architect. Create a technical design for this feature.

    Issue: {issue_url}
    Technical Approach: {technical_approach}

    Your job:
    1. Read the issue and technical assessment
    2. Create a detailed architecture document
    3. Define design patterns to follow
    4. Specify API contracts and interfaces
    5. Submit the architecture doc as a PR
    6. Post a summary comment on the issue

    Follow ADR format for architecture decisions.

  validation:
    required_outputs: ["architecture_doc_url", "design_patterns"]
