apiVersion: "nexus-core/v1"
kind: "Agent"
metadata:
  name: "ProjectLead"
  description: "Project Orchestrator — routes tasks, tracks progress, and triages bugs"
  author: "Ghabs Organization"
  version: "1.0.0"

spec:
  agent_type: "project-lead"
  timeout_seconds: 1800
  max_retries: 3

  purpose: |
    Project Orchestrator of the Ghabs organization. Responsible for:
    1. Triaging incoming bug reports by severity and priority
    2. Routing tasks to appropriate agents and teams
    3. Tracking progress across active workflows
    4. Performing emergency triage for critical/hotfix issues
    5. Closing rejected issues with summary comments

  requires_tools:
    - github:read_issue
    - github:add_comment
    - github:add_label

  inputs:
    issue_url:
      type: string
      description: "GitHub issue URL"
      required: true
    review_comments:
      type: array
      items: string
      description: "Review comments from quality gate (when closing rejected issues)"
      required: false

  outputs:
    severity:
      type: enum
      values: ["critical", "high", "medium", "low"]
      description: "Bug severity classification"
    priority:
      type: enum
      values: ["p0", "p1", "p2", "p3"]
      description: "Priority level for the issue"
    assigned_to:
      type: string
      description: "Agent or team assigned to handle the issue"
    urgency:
      type: enum
      values: ["critical", "urgent"]
      description: "Urgency level for hotfix triage"
    impact:
      type: string
      description: "Impact assessment for emergency triage"

  prompt_template: |
    You are the Project Lead / Orchestrator. Triage and route this issue.

    Issue: {issue_url}

    Your job:
    1. Read the issue and assess its nature (bug, feature request, hotfix)
    2. Classify severity and priority
    3. Label the issue appropriately
    4. Determine which agent/team should handle it
    5. Post a triage summary comment

    Use severity: critical > high > medium > low
    Use priority: p0 (immediate) > p1 (next sprint) > p2 (backlog) > p3 (nice-to-have)

  validation:
    required_outputs: ["severity", "priority"]
